services:
  calendar-bike-omsk:
    image: ${CALENDAR_BIKE_OMSK_IMAGE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar-bike-omsk.rule=Host(`${OMSK_BIKE_DOMAIN}`)"
      - "traefik.http.routers.calendar-bike-omsk.entrypoints=websecure"
      - "traefik.http.routers.calendar-bike-omsk.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-myresolver}"
      - "traefik.http.routers.calendar-bike-omsk.tls.domains[0].main=${OMSK_BIKE_DOMAIN}"
      - "traefik.http.routers.calendar-bike-omsk.middlewares=calendar-bike-omsk-compress"
      - "traefik.http.middlewares.calendar-bike-omsk-compress.compress=true"
    logging:
      driver: json-file
      options:
        max-size: "50m"
    networks:
      traefik:
        aliases:
          - calendar-bike-omsk

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK:-theta-brige}
